---
name: Article crawling
about: download an Internet article automatically, then transform it to Markdown file & save it to the repository
title: (replace this with the article title)
labels:
  - crawler
---

@your-org/your-team I add a new article to translate or publish:

https://example.com/replace/this/with/your/original/article/URL
